### ISSUE TITLE
can't run executables with jsystem on linux

### ISSUE THREAD

**Issue by benbarrowes** [avivrosenberg/matlab-jsystem#1]
Maybe I am not understanding something, but I can't seem to run executables using jsystem on Linux. My linux system is:
Linux barrowes 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Matlab version in 2017a.

For example, if I want to run an emacs window from within matlab, I can do this:
>> [a,b]=system('emacs &')
a =
     0
b =
  0×0 empty char array
>>
And I get an emacs window appear.

But if I try that with jsystem, I get:
>> [a,b,c]=jsystem('emacs &')
a =
     0
b =
  0×0 empty char array
c =
    'emacs: /usr/local/MATLAB/R2017a/bin/glnxa64/libtiff.so.5: no version information available (required 
by emacs)                                                                                                
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.9' not found (requ
ired by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)                                                     
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (re
quired by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)                                                   
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.9' not found (requ
ired by /usr/lib/x86_64-linux-gnu/libmircommon.so.7)                                                     
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (re
quired by /usr/lib/x86_64-linux-gnu/libmircommon.so.7)                                                   
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.9' not found (requ
ired by /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3)                                                   
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (re
quired by /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3)                                                 
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.9' not found (requ
ired by /usr/lib/x86_64-linux-gnu/libmircore.so.1)                                                       
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (re
quired by /usr/lib/x86_64-linux-gnu/libmircore.so.1)                                                     
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (re
quired by /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0)                                           
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (re
quired by /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9)                                               
     emacs: /usr/local/MATLAB/R2017a/sys/os/glnxa64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (re
quired by /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0)'                                      
>> 

And this happens even when I try to run emacs in --batch mode with no window.

If I try to specify my csh, I get this:

>> [a,b,c]=jsystem('emacs &','/bin/csh')
a =
     1
b =
  0×0 empty char array
c =
    'emacs &: No such file or directory.'
>>

And specifying the path to emacs doesn't seem to work either:

>> [a,b,c]=jsystem('/usr/bin/emacs &','/bin/csh')    
a =
     1
b =
  0×0 empty char array
c =
    '/usr/bin/emacs &: No such file or directory.'
>> 

Even though emacs is in that directory.

**Comment by avivrosenberg** [comment]
Hi,

First of all, does the `jsystem_benchmark` script run properly?

Second, you seem to have two separate problems here.
In the first invocation you tried (`[a,b,c]=jsystem('emacs &')`) it seems that the environment of the matlab process has a library path (see `LD_LIBRARY_PATH` env var) that doesn't include the libs emacs needs or their proper versions. Not sure why it works with `system` however.

In the next two invocations where you specify the shell `/bin/csh`, you need to specify it as `/bin/csh -c`. Maybe I should add the `-c` flag automatically though...
Even if you do this, the shell you start will  inherit it's environment from the parent process so if I'm right about the first problem you might still see it, unless that var is changed by the init scripts of your shell.

You can also try without a shell (use `noshell` as the second argument), but then you won't be able to run the process in the background (i.e. with `&`).

Hope this helps.

**Comment by benbarrowes** [comment]
Hi Aviv,

jsystem_benchmark runs fine.

I traced the problem back to a libc incompatibility:
https://www.mathworks.com/matlabcentral/answers/329796-issue-with-libstdc-so-6

If I use LD_PRELOAD as they suggest, emacs works fine through jsystem. I am not sure it works with system, though.

Thanks,
bb
